export const types = {
  SET_LOADING_TRUE: "SET_LOADING_TRUE",
  GET_PRODUCT_START: "GET_PRODUCT_START",
  GET_PRODUCT_SUCCESS: "GET_PRODUCT_SUCCESS",
  GET_SINGLE_PRODUCT_START: "GET_SINGLE_PRODUCT",
  GET_SINGLE_PRODUCT_SUCCESS: "GET_SINGLE_PRODUCT_SUCCESS",
  REMOVE_CURRENT_PRODUCT: "REMOVE_CURRENT_PRODUCT",
  LOGIN: "LOGIN",
  LOGOUT: "LOGOUT",
  ADD_PRODUCT_TO_CART: "ADD_PRODUCT_TO_CART",
  REMOVE_PRODUCT_TO_CART: "REMOVE_PRODUCT_TO_CART",
};
